DSOS-1570: weblogic cert fix (#20)
* DSOS-1570: weblogic: add latest patches to setup script

* weblogic setup script fix

* test

* test

* test

* test

* test

* test

* test

* test

* fix nbsp

* test

* fix

* fix

* test

* fix

diff --git a/ansible/roles/weblogic/templates/10.3/weblogic-setup.sh.j2 b/ansible/roles/weblogic/templates/10.3/weblogic-setup.sh.j2
--- a/ansible/roles/weblogic/templates/10.3/weblogic-setup.sh.j2
+++ b/ansible/roles/weblogic/templates/10.3/weblogic-setup.sh.j2
@@ -62,6 +62,84 @@ oracle_commands() {
     sed -i 's/${DB_USERNAME}/'${DB_USERNAME}'/g' /u01/software/weblogic/tagsar.properties /u01/software/weblogic/hotpage.properties /u01/software/weblogic/autologoff.properties
     sed -i 's/${DB_PASSWORD}/'${DB_PASSWORD}'/g' /u01/software/weblogic/tagsar.properties /u01/software/weblogic/hotpage.properties /u01/software/weblogic/autologoff.properties
 
+    # Set WLS environment
+    echo "# set WLS env"
+    . $WL_HOME/server/bin/setWLSEnv.sh
+
+    # Undo previous patch
+    echo "# get previous patch ID"
+    cd $WL_HOME/../utils/bsu/
+    current_patch_ids=$(./bsu.sh -view -status=applied -prod_dir=$WL_HOME | grep "^Patch ID:" | cut -d: -f2 | sed  's/^ *//g' | cut -d\  -f1)
+    if [[ $(echo "$current_patch_ids" | wc -l) > 1 ]]; then
+      echo "ERROR: Not implemented multiple patches uninstall"
+      exit 1
+    fi
+    if [[ ! -z $current_patch_ids ]]; then
+      echo "# Removing previous patch: ./bsu.sh -remove -patchlist=$current_patch_ids -prod_dir=$WL_HOME -verbose"
+      ./bsu.sh -remove -patchlist=$current_patch_ids -prod_dir=$WL_HOME -verbose
+
+      # Display current patch, both for debug + to introduce a slight delay
+      current_patch_ids=$(./bsu.sh -view -status=applied -prod_dir=$WL_HOME | grep "^Patch ID:" | cut -d: -f2 | sed  's/^ *//g' | cut -d\  -f1)
+      if [[ ! -z $current_patch_ids ]]; then
+        echo "ERROR: failed to remove previous patch"
+        exit 1
+      fi
+    fi
+
+    # Apply latest patch
+    patch_s3_path="ec2-image-builder-nomis20220314103938567000000001/weblogic-software"
+    patch_file="p32832785_1036_Generic.zip"
+    patch_dir="$WL_HOME/../utils/bsu/cache_dir"
+    target_patch_id="3NVW"
+    if [[ -e $patch_dir ]]; then
+      echo "# rm -rf $patch_dir"
+      rm -rf $patch_dir
+    fi
+    echo "# mkdir -p $patch_dir"
+    mkdir -p "$patch_dir"
+    cd $patch_dir
+    echo "# aws s3 cp s3://$patch_s3_path/$patch_file ./$patch_file --no-progress"
+    aws s3 cp "s3://$patch_s3_path/$patch_file" "./$patch_file" --no-progress
+    echo "# unzip $patch_file"
+    unzip $patch_file
+    cd $WL_HOME/../utils/bsu/
+    echo "# Apply patch: ./bsu.sh -install -patch_download_dir=$patch_dir -patchlist=$target_patch_id -prod_dir=$WL_HOME -verbose"
+    ./bsu.sh -install -patch_download_dir=$patch_dir -patchlist=$target_patch_id -prod_dir=$WL_HOME -verbose
+
+    # Check installed
+    current_patch_ids=$(./bsu.sh -view -status=applied -prod_dir=$WL_HOME | grep "^Patch ID:" | cut -d: -f2 | sed  's/^ *//g' | cut -d\  -f1)
+    if (! echo "$current_patch_ids" | grep $target_patch_id > /dev/null ); then
+      echo ERROR: failed to install patch $target_patch_id. Got: $current_patch_ids
+      exit 1
+    fi
+
+    # Apply certificate patch
+    patch_s3_path="ec2-image-builder-nomis20220314103938567000000001/weblogic-software"
+    patch_file="p13964737_10360210720_Generic.zip"
+    patch_dir="$WL_HOME/../utils/bsu/cache_dir"
+    target_patch_id="UEYM"
+    if [[ -e $patch_dir ]]; then
+      echo "# rm -rf $patch_dir"
+      rm -rf $patch_dir
+    fi
+    echo "# mkdir -p $patch_dir"
+    mkdir -p "$patch_dir"
+    cd $patch_dir
+    echo "# aws s3 cp s3://$patch_s3_path/$patch_file ./$patch_file --no-progress"
+    aws s3 cp "s3://$patch_s3_path/$patch_file" "./$patch_file" --no-progress
+    echo "# unzip $patch_file"
+    unzip $patch_file
+    cd $WL_HOME/../utils/bsu/
+    echo "# Apply patch: ./bsu.sh -install -patch_download_dir=$patch_dir -patchlist=$target_patch_id -prod_dir=$WL_HOME -verbose"
+    ./bsu.sh -install -patch_download_dir=$patch_dir/$patch_file -patchlist=$target_patch_id -prod_dir=$WL_HOME -verbose
+
+    # Check installed
+    current_patch_ids=$(./bsu.sh -view -status=applied -prod_dir=$WL_HOME | grep "^Patch ID:" | cut -d: -f2 | sed  's/^ *//g' | cut -d\  -f1)
+    if (! echo "$current_patch_ids" | grep $target_patch_id > /dev/null ); then
+      echo ERROR: failed to install patch $target_patch_id. Got: $current_patch_ids
+      exit 1
+    fi
+
     echo "# running /u01/app/oracle/Middleware/forms_home/bin/config.sh"
     yes | bash /u01/app/oracle/Middleware/forms_home/bin/config.sh -silent -response /u01/software/forms/configure_only.rsp -invPtrLoc /var/opt/oracle/oraInst.loc
 
@@ -77,6 +155,21 @@ oracle_commands() {
     # Copy configuration files
     echo "# moving config files to correct locations"
     copy_managed_server_files
+
+    # Create new cert
+    echo "# create new cert"
+    mkdir ~/key
+    cd ~/key
+    java utils.CertGen -keyfilepass DemoIdentityPassPhrase -certfile democert -keyfile demokey -strength 1024
+    echo "# import private key"
+    java utils.ImportPrivateKey -keystore DemoIdentity.jks -storepass DemoIdentityKeyStorePassPhrase -keyfile demokey.pem -keyfilepass DemoIdentityPassPhrase -certfile democert.pem -alias demoidentity
+    echo "# list keys"
+    keytool -list -v -keystore DemoIdentity.jks -storepass DemoIdentityKeyStorePassPhrase
+    echo "# import cert"
+    keytool -importcert -trustcacerts -alias wlscertgenca -keystore DemoTrust.jks -storepass DemoTrustKeyStorePassPhrase -file /u01/app/oracle/Middleware/wlserver_10.3/server/lib/CertGenCA.der -noprompt
+    echo "Update nodemanager.properties"
+    sed -i 's/SecureListener=true/SecureListener=false/g' /u01/app/oracle/Middleware/wlserver_10.3/common/nodemanager/nodemanager.properties
+    sed -i '/<node-manager>/a \      <nm-type>Plain</nm-type>' /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/config/config.xml
 
     # Apply patches
     echo "# running setDomainEnv.sh"
@@ -102,8 +195,6 @@ oracle_commands() {
     cd $ORACLE_HOME/reports/lib && /usr/bin/make -f ins_reports.mk install
 
     # Start node manager and weblogic as daemon processes
-    echo "# set WLS env"
-    . $WL_HOME/server/bin/setWLSEnv.sh
     echo "# startNodeManager"
     nohup /u01/app/oracle/Middleware/wlserver_10.3/server/bin/startNodeManager.sh >>nohup.out 2>&1 &
     echo "# startWebLogic"
@@ -111,9 +202,29 @@ oracle_commands() {
     echo "# opmnctl startall"
     opmnctl startall
 
-    # Check db connection & Compile forms
-    echo "# Compile forms and check DB connection"
-    /u01/tag/utils/scripts/doallforms.sh -s /u01/tag/FormsSources -o /u01/tag/FormsObjects -e "${DB_NAME}" -p ${DB_PASSWORD}
+    # Compile forms
+    echo "# Compile forms: /u01/tag/utils/scripts/doallforms.sh -s /u01/tag/FormsSources -o /u01/tag/FormsObjects -e '${DB_HOSTNAME}/${DB_NAME}' -p 'xxxx'"
+    /u01/tag/utils/scripts/doallforms.sh -s /u01/tag/FormsSources -o /u01/tag/FormsObjects -e "${DB_HOSTNAME}/${DB_NAME}" -p ${DB_PASSWORD}
+
+    # Restart node manager (seems to be required for it to take the nm-type)
+    opmnctl stopall || true
+    /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/bin/stopWebLogic.sh || true
+    pkill -u oracle startNodeManage || true
+    pkill -u oracle startWebLogic.s || true
+    pkill -u oracle java || true
+    pkill -9 -u oracle startNodeManage || true
+    pkill -9 -u oracle startWebLogic.s || true
+    pkill -9 -u oracle java || true
+
+    # Start node manager and weblogic as daemon processes
+    echo "# startNodeManager"
+    nohup /u01/app/oracle/Middleware/wlserver_10.3/server/bin/startNodeManager.sh >>nohup.out 2>&1 &
+    echo "# startWebLogic"
+    nohup /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/bin/startWebLogic.sh >>nohup.out 2>&1 &
+    echo "# opmnctl startall"
+    opmnctl startall
+    echo "# wait for everything to come up"
+    sleep 180
 
     # Create Managed Servers
     # (i) Autologoff
