fix

diff --git a/ansible/roles/weblogic/templates/10.3/weblogic-setup.sh.j2 b/ansible/roles/weblogic/templates/10.3/weblogic-setup.sh.j2
--- a/ansible/roles/weblogic/templates/10.3/weblogic-setup.sh.j2
+++ b/ansible/roles/weblogic/templates/10.3/weblogic-setup.sh.j2
@@ -206,19 +206,39 @@ oracle_commands() {
     echo "# Compile forms: /u01/tag/utils/scripts/doallforms.sh -s /u01/tag/FormsSources -o /u01/tag/FormsObjects -e '${DB_HOSTNAME}/${DB_NAME}' -p 'xxxx'"
     /u01/tag/utils/scripts/doallforms.sh -s /u01/tag/FormsSources -o /u01/tag/FormsObjects -e "${DB_HOSTNAME}/${DB_NAME}" -p ${DB_PASSWORD}
 
+    # Restart node manager (seems to be required for it to take the nm-type)
+    opmnctl stopall || true
+    /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/bin/stopWebLogic.sh || true
+    pkill -u oracle startNodeManage || true
+    pkill -u oracle startWebLogic.s || true
+    pkill -u oracle java || true
+    pkill -9 -u oracle startNodeManage || true
+    pkill -9 -u oracle startWebLogic.s || true
+    pkill -9 -u oracle java || true
+
+    # Start node manager and weblogic as daemon processes
+    echo "# startNodeManager"
+    nohup /u01/app/oracle/Middleware/wlserver_10.3/server/bin/startNodeManager.sh >>nohup.out 2>&1 &
+    echo "# startWebLogic"
+    nohup /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/bin/startWebLogic.sh >>nohup.out 2>&1 &
+    echo "# opmnctl startall"
+    opmnctl startall
+    echo "# wait for everything to come up"
+    sleep 180
+
     # Create Managed Servers
     # (i) Autologoff
-    ##echo "# Create Managed Servers Autologoff"
-    ##java weblogic.WLST /u01/software/weblogic/create_managed_app.py -p /u01/software/weblogic/autologoff.properties
+    echo "# Create Managed Servers Autologoff"
+    java weblogic.WLST /u01/software/weblogic/create_managed_app.py -p /u01/software/weblogic/autologoff.properties
     # (ii) Create TagSar
-    ##echo "# Create Managed Servers TagSar"
-    ##java weblogic.WLST /u01/software/weblogic/create_managed_app.py -p /u01/software/weblogic/tagsar.properties
+    echo "# Create Managed Servers TagSar"
+    java weblogic.WLST /u01/software/weblogic/create_managed_app.py -p /u01/software/weblogic/tagsar.properties
     # (iii) Create HotPage
-    ##echo "# Create Managed Servers HotPage"
-    ##java weblogic.WLST /u01/software/weblogic/create_managed_app.py -p /u01/software/weblogic/hotpage.properties
+    echo "# Create Managed Servers HotPage"
+    java weblogic.WLST /u01/software/weblogic/create_managed_app.py -p /u01/software/weblogic/hotpage.properties
 
-    ##echo "# Cleanup"
-    ##rm -f /u01/software/weblogic/tagsar.properties /u01/software/weblogic/hotpage.properties /u01/software/weblogic/autologoff.properties
+    echo "# Cleanup"
+    rm -f /u01/software/weblogic/tagsar.properties /u01/software/weblogic/hotpage.properties /u01/software/weblogic/autologoff.properties
 }
 
 copy_managed_server_files() {
