DSOS-1614: nomis weblogic ansible tidy up

diff --git a/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/opmn b/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/opmn
--- a/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/opmn
+++ b/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/opmn
@@ -8,98 +8,117 @@
 # Source function library.
 . /etc/init.d/functions
 
-RETVAL=0
 prog=opmn
 
 start_process() {
-  su - oracle -c "opmnctl startall" | logger -p local3.info -t $prog
+  if [[ $(whoami) == "root" ]]; then
+    su - oracle -c "opmnctl startall" | logger -p local3.info -t $prog
+  else
+    echo -n "must be run as root"
+    return 1
+  fi
 }
 
-wait_process() {
-  sleep 2
+stop_process() {
+  if [[ $(whoami) == "root" ]]; then
+    su - oracle -c "opmnctl stopall" | logger -p local3.info -t $prog
+  else
+    echo -n "must be run as root"
+    return 1
+  fi
+}
+
+status_process() {
+  if [[ $(whoami) == "root" ]]; then
+    su - oracle -c "opmnctl status"
+  else
+    echo "must be run as root"
+    return 1
+  fi
 }
 
 get_process_pids() {
-  local process_pids
   ! process_pids=$(pgrep -u oracle -f "opmn" 2> /dev/null) && return 1
-  for process_pid in $process_pids; do
-    pstree -ap $process_pid  | grep -v '{' | cut -d, -f2 | cut -d\  -f1
-  done
+  (
+    for process_pid in $process_pids; do
+      pstree -ap "$process_pid" | grep -v '{' | cut -d, -f2 | cut -d\  -f1
+    done
+  ) | sort -u | tr '\n' ' '
 }
 
 start() {
-        echo -n $"Starting $prog: "
-        if PIDS=$(get_process_pids); then
-          echo -n Already running $PIDS && echo_failure
-          echo
-          return 1
-        fi
-        echo "init.d starting $prog" | logger -p local3.info -t $prog
-        start_process
-        wait_process
-        if ! get_process_pids > /dev/null; then
-          echo_failure
-          RETVAL=1
-        else
-          echo_success
-        fi
-        echo
-        return $RETVAL
+  echo -n $"Starting $prog: "
+  if PIDS=$(get_process_pids); then
+    echo -n "Already running $PIDS"
+    echo_failure
+    echo
+    return 1
+  fi
+  echo "init.d starting $prog" | logger -p local3.info -t $prog
+  if ! start_process; then
+    echo_failure
+    echo
+    return 1
+  fi
+  if ! get_process_pids > /dev/null; then
+    echo_failure
+    echo
+    return 1
+  fi
+  echo_success
+  echo
 }
 
 stop() {
-        echo -n $"Shutting down $prog: "
-        if ! PIDS=$(get_process_pids); then
-          echo -n "process not found" && echo_failure
-          echo
-          return 1
-        fi
-        echo init.d killing $prog $PIDS | logger -p local3.info -t $prog
-        su - oracle -c "opmnctl stopall" | logger -p local3.info -t $prog
-        sleep 2
-        if get_process_pids > /dev/null; then
-          echo_failure
-          RETVAL=1
-        else
-          echo_success
-        fi
-        echo
-        return $RETVAL
+  echo -n $"Shutting down $prog: "
+  if ! PIDS=$(get_process_pids); then
+    echo -n "process not found"
+    echo_failure
+    echo
+    return 1
+  fi
+  echo "init.d killing $prog $PIDS" | logger -p local3.info -t "$prog"
+  if ! stop_process; then
+    echo_failure
+    echo
+    return 1
+  fi
+  if get_process_pids > /dev/null; then
+    echo_failure
+    echo
+    return 1
+  fi
+  echo_success
+  echo
 }
 
 status() {
-        echo -n $"Status of $prog: "
-        if ! PIDS=$(get_process_pids); then
-          echo -n "process not found" && echo_failure
-          echo
-          return 1
-        fi
-        echo -n $PIDS && echo_success
-        echo
-        return $RETVAL
+  echo -n $"Status of $prog: "
+  status_process
+  return $?
 }
 
 restart() {
-        stop
-        start
+  stop
+  start
 }
 
 case "$1" in
   start)
-        start
-        ;;
+    start
+    ;;
   stop)
-        stop
-        ;;
+    stop
+    ;;
   restart)
-        restart
-        ;;
+    restart
+    ;;
   status)
-        status
-        ;;
+    status
+    ;;
   *)
-        echo "Usage: $0 {start|stop|restart|status}"
-        exit 3
+    echo "Usage: $0 {start|stop|restart|status}"
+    exit 3
 esac
 
 exit $?
