DSOS-1614: weblogic mop up (#23)
* DSOS-1614: nomis weblogic ansible tidy up

* add ansible-requirements role

* Updated ansible requirements

* added image builder bucket to groupvars

* fix script

* fix

* fix

* Commit changes made by code formatters

* fix

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-node-manager b/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-node-manager
--- a/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-node-manager
+++ b/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-node-manager
@@ -8,98 +8,110 @@
 # Source function library.
 . /etc/init.d/functions
 
-RETVAL=0
-prog=weblogic-node-manager
+prog="weblogic-node-manager"
 
 start_process() {
-  nohup su - oracle -c /u01/app/oracle/Middleware/wlserver_10.3/server/bin/startNodeManager.sh 2>&1 | logger -p local3.info -t $prog &
+  if [[ $(whoami) == "root" ]]; then
+    nohup su - oracle -c /u01/app/oracle/Middleware/wlserver_10.3/server/bin/startNodeManager.sh 2>&1 | logger -p local3.info -t "$prog" &
+  else
+    echo -n "must be run as root"
+    return 1
+  fi
 }
 
 wait_process() {
-  timeout 60 /home/oracle/admin/scripts/wait_for_entry_in_log.sh /var/log/messages "listener started" "${prog}:"
+  timeout 60 /home/oracle/admin/scripts/wait_for_entry_in_log.sh /var/log/messages "listener started" "$prog:"
 }
 
 get_process_pids() {
-  local process_pids
-  ! process_pids=$(pgrep -u oracle -f "startNodeManager.sh$" 2> /dev/null) && return 1
-  for process_pid in $process_pids; do
-    pstree -ap $process_pid  | grep -v '{' | cut -d, -f2 | cut -d\  -f1
-  done
+  process_pids1=$(pgrep -u oracle -f "startNodeManager.sh$" 2> /dev/null)
+  process_pids2=$(pgrep -u oracle -f "weblogic.NodeManager" 2> /dev/null)
+  [[ -z $process_pids1 && -z $process_pids2 ]] && return 1
+  (
+    for process_pid in $process_pids1 $process_pids2; do
+      pstree -ap "$process_pid" | grep -v '{' | cut -d, -f2 | cut -d\  -f1
+    done
+  ) | sort -u | tr '\n' ' '
 }
 
 start() {
-        echo -n $"Starting $prog: "
-        if PIDS=$(get_process_pids); then
-          echo -n Already running $PIDS && echo_failure
-          echo
-          return 1
-        fi
-        echo "init.d starting $prog" | logger -p local3.info -t $prog
-        start_process
-        wait_process
-        if ! get_process_pids > /dev/null; then
-          echo_failure
-          RETVAL=1
-        else
-          echo_success
-        fi
-        echo
-        return $RETVAL
+  echo -n $"Starting $prog: "
+  if PIDS=$(get_process_pids); then
+    echo -n "Already running $PIDS"
+    echo_failure
+    echo
+    return 1
+  fi
+  echo "init.d starting $prog" | logger -p local3.info -t "$prog"
+  if ! start_process; then
+    echo_failure
+    echo
+    return 1
+  fi
+  wait_process
+  if ! get_process_pids > /dev/null; then
+    echo_failure
+    echo
+    return 1
+  fi
+  echo_success
+  echo
 }
 
 stop() {
-        echo -n $"Shutting down $prog: "
-        if ! PIDS=$(get_process_pids); then
-          echo -n "process not found" && echo_failure
-          echo
-          return 1
-        fi
-        echo init.d killing $prog $PIDS | logger -p local3.info -t $prog
-        kill $PIDS
-        sleep 2
-        if get_process_pids > /dev/null; then
-          echo_failure
-          RETVAL=1
-        else
-          echo_success
-        fi
-        echo
-        return $RETVAL
+  echo -n $"Shutting down $prog: "
+  if ! PIDS=$(get_process_pids); then
+    echo -n "process not found"
+    echo_failure
+    echo
+    return 1
+  fi
+  echo "init.d killing $prog $PIDS" | logger -p local3.info -t "$prog"
+  kill $PIDS
+  sleep 2
+  if get_process_pids > /dev/null; then
+    echo_failure
+    echo
+    return 1
+  fi
+  echo_success
+  echo
 }
 
 status() {
-        echo -n $"Status of $prog: "
-        if ! PIDS=$(get_process_pids); then
-          echo -n "process not found" && echo_failure
-          echo
-          return 1
-        fi
-        echo -n $PIDS && echo_success
-        echo
-        return $RETVAL
+  echo -n $"Status of $prog: "
+  if ! PIDS=$(get_process_pids); then
+    echo -n "process not found"
+    echo_failure
+    echo
+    return 1
+  fi
+  echo -n "$PIDS"
+  echo_success
+  echo
 }
 
 restart() {
-        stop
-        start
+  stop
+  start
 }
 
 case "$1" in
   start)
-        start
-        ;;
+    start
+    ;;
   stop)
-        stop
-        ;;
+    stop
+    ;;
   restart)
-        restart
-        ;;
+    restart
+    ;;
   status)
-        status
-        ;;
+    status
+    ;;
   *)
-        echo "Usage: $0 {start|stop|restart|status}"
-        exit 3
+    echo "Usage: $0 {start|stop|restart|status}"
+    exit 3
 esac
 
 exit $?
