add logging

diff --git a/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-server b/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-server
--- a/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-server
+++ b/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-server
@@ -20,7 +20,7 @@ start_process() {
 }
 
 wait_process() {
-  timeout 590 /home/oracle/admin/scripts/wait_for_entry_in_log.sh /var/log/messages "Server started in RUNNING mode" "$prog:"
+  timeout 290 /home/oracle/admin/scripts/wait_for_entry_in_log.sh /var/log/messages "Server started in RUNNING mode" "$prog:"
 }
 
 get_process_pids() {
@@ -44,16 +44,24 @@ start() {
   fi
   echo "init.d starting $prog" | logger -p local3.info -t "$prog"
   if ! start_process; then
+    echo "init.d failed starting $prog" | logger -p local3.info -t "$prog"
     echo_failure
     echo
     return 1
   fi
-  wait_process
+  if ! wait_process; then
+    echo "init.d failed waiting for $prog" | logger -p local3.info -t "$prog"
+    echo_failure
+    echo
+    return 1
+  fi
   if ! get_process_pids > /dev/null; then
+    echo "init.d failed getting process pids for $prog" | logger -p local3.info -t "$prog"
     echo_failure
     echo
     return 1
   fi
+  echo "init.d started $prog" | logger -p local3.info -t "$prog"
   echo_success
   echo
 }
