nomis: DSOS-1820: weblogic init script tweaks (#147)
* repair automatically on boot

* increase timeout for startup

* increase timeout for startup

* add logging

* test

* Revert timeout change

diff --git a/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-node-manager b/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-node-manager
--- a/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-node-manager
+++ b/ansible/roles/nomis-weblogic/templates/10.3/etc/init.d/weblogic-node-manager
@@ -44,16 +44,21 @@ start() {
   fi
   echo "init.d starting $prog" | logger -p local3.info -t "$prog"
   if ! start_process; then
+    echo "init.d failed starting $prog" | logger -p local3.info -t "$prog"
     echo_failure
     echo
     return 1
   fi
-  wait_process
+  if ! wait_process; then
+    echo "init.d failed waiting for $prog" | logger -p local3.info -t "$prog"
+  fi
   if ! get_process_pids > /dev/null; then
+    echo "init.d failed getting process pids for $prog" | logger -p local3.info -t "$prog"
     echo_failure
     echo
     return 1
   fi
+  echo "init.d started $prog" | logger -p local3.info -t "$prog"
   echo_success
   echo
 }
