correct collectd settings and more explanation in readme

diff --git a/ansible/roles/amazon-cloudwatch-agent/templates/oracle_health.sh.j2 b/ansible/roles/amazon-cloudwatch-agent/templates/oracle_health.sh.j2
--- a/ansible/roles/amazon-cloudwatch-agent/templates/oracle_health.sh.j2
+++ b/ansible/roles/amazon-cloudwatch-agent/templates/oracle_health.sh.j2
@@ -10,7 +10,7 @@ fi
 export PATH=${PATH}:/usr/local/bin
 
 # Templated in from ansible
-HOSTNAME="${HOSTNAME}" 
+HOSTNAME="${HOSTNAME:-localhost}"
 INTERVAL="{{ collectd_script_interval }}"
 ORACLE_SID_LIST="{{ oracle_sid_list }}"
 ORACLE_BATCH_ERROR_FILE="{{ oracle_batch_error_file }}"
@@ -60,37 +60,37 @@ batch_status() {
         then
             return "$val"
         else
-            echo "db error for $LINE is not a number" 1>&2
+            echo "batch error value for $LINE is not a valid number" 1>&2
             return 2
         fi
     else
-        echo "no match for $LINE" 1>&2
+        echo "no batch status entry for $LINE" 1>&2
         return 2
     fi
 }
 
 while sleep "$INTERVAL"
 do
-    for SID in ${LIST}
+    for SID in ${ORACLE_SID_LIST}
     do            
         ORACLE_SID="+ASM"
         ORAENV_ASK="NO"
         . oraenv > /dev/null
         db_connected
         returnval=$?
-        echo "PUTVAL \"$HOSTNAME-$SID/exec-oracle-health/bool\" interval=$INTERVAL N:$returnval"
+        echo "PUTVAL $HOSTNAME/exec-db_connected/bool-$SID interval=$INTERVAL N:$returnval"
     done
 
 
     if [[ -s "${ORACLE_BATCH_ERROR_FILE}" ]]
     then
-        for LINE in ${ORACLE_BATCH_STATUSES}
+        for text in $ORACLE_BATCH_STATUSES
         do
-            batch_status "$LINE" "$ORACLE_BATCH_ERROR_FILE"
+            batch_status "$text" "$ORACLE_BATCH_ERROR_FILE"
             status=$?
-            echo "PUTVAL \"$HOSTNAME-$LINE/exec-oracle-batch-status/graph\" interval=$INTERVAL N:$status"
+            echo "PUTVAL $HOSTNAME/exec-batch_error/gauge-$text interval=$INTERVAL N:$status"
         done
     else
-        echo "issue with file" 
+        echo "PUTVAL $HOSTNAME/exec-file_error/gauge interval=$INTERVAL N:2"
     fi
 done
