Commit changes made by code formatters

diff --git a/ansible/roles/nomis-release-deployment/tasks/install-nomis-releases.yml b/ansible/roles/nomis-release-deployment/tasks/install-nomis-releases.yml
--- a/ansible/roles/nomis-release-deployment/tasks/install-nomis-releases.yml
+++ b/ansible/roles/nomis-release-deployment/tasks/install-nomis-releases.yml
@@ -90,34 +90,34 @@
     - name: Deploy release
       become_user: oracle
       ansible.builtin.shell: |
-         set -eo pipefail
-         get_status() {
-           sqlplus  -s {{ app_db_username }}/{{ app_db_password }}@{{ app_db_name }} <<EOF
-           set head off feedback off
-           select 'RELEASE_STATUS='||count(1) from db_patches where profile_code='TAG' and profile_value like '{{ item }}';
-           exit
-         EOF
-         }
-         insert_status() {
-           sqlplus  -s {{ app_db_username }}/{{ app_db_password }}@{{ app_db_name }} <<EOF
-           set head off feedback off
-           insert into db_patches (profile_code,profile_value ) values ('TAG','{{ item }}');
-           commit;
-           exit
-         EOF
-         }
-         main() {
-           . ~/.bash_profile
-           cd /u01/releases/{{ item }}
+        set -eo pipefail
+        get_status() {
+          sqlplus  -s {{ app_db_username }}/{{ app_db_password }}@{{ app_db_name }} <<EOF
+          set head off feedback off
+          select 'RELEASE_STATUS='||count(1) from db_patches where profile_code='TAG' and profile_value like '{{ item }}';
+          exit
+        EOF
+        }
+        insert_status() {
+          sqlplus  -s {{ app_db_username }}/{{ app_db_password }}@{{ app_db_name }} <<EOF
+          set head off feedback off
+          insert into db_patches (profile_code,profile_value ) values ('TAG','{{ item }}');
+          commit;
+          exit
+        EOF
+        }
+        main() {
+          . ~/.bash_profile
+          cd /u01/releases/{{ item }}
 
-           echo {{ item }}: ./db_patch.sh -d {{ app_db_name }} -p xxx
-           # ./db_patch.sh -d {{ app_db_name }} -p {{ app_db_password }}
-           # insert_status
-           status=$(get_status | egrep -o "RELEASE_STATUS=[[:digit:]]+" | cut -d= -f2)
-           if [[ -z $status || $status -eq 0 ]]; then
-             echo "Failed deployment"
-             exit 1
-           fi
-         }
-         main 2>&1 | logger -p local3.info -t ansible-nomis-release-deployment
+          echo {{ item }}: ./db_patch.sh -d {{ app_db_name }} -p xxx
+          # ./db_patch.sh -d {{ app_db_name }} -p {{ app_db_password }}
+          # insert_status
+          status=$(get_status | egrep -o "RELEASE_STATUS=[[:digit:]]+" | cut -d= -f2)
+          if [[ -z $status || $status -eq 0 ]]; then
+            echo "Failed deployment"
+            exit 1
+          fi
+        }
+        main 2>&1 | logger -p local3.info -t ansible-nomis-release-deployment
       loop: "{{ download_release|default([]) }}"
