Fixes for detecting local dbs and deploying cred store

diff --git a/ansible/roles/nomis-goldengate-19c/tasks/configure_credential_store.yml b/ansible/roles/nomis-goldengate-19c/tasks/configure_credential_store.yml
--- a/ansible/roles/nomis-goldengate-19c/tasks/configure_credential_store.yml
+++ b/ansible/roles/nomis-goldengate-19c/tasks/configure_credential_store.yml
@@ -13,48 +13,56 @@
       ansible.builtin.set_fact:
         gg_home_exists: "{{ gg_home_exists.stat.exists }}"
 
+    # Add processing to only add those credentials for database groups that are being deployed to i.e. if not deploying to MIS database then skip adding credentials for the MIS database connection alias as these will not be required and may not exist if the MIS database is not being deployed to by GoldenGate.
     - name: Execute credential store configuration commands
       when: gg_home_exists
       ansible.builtin.shell: |
-        # Retrieve ggadmin passwords from AWS Secrets Manager
-        ggadmin_source_pwd=$(aws secretsmanager get-secret-value \
-          --secret-id "/oracle/database/{{ oracle_goldengate_group.source.tns_alias }}/passwords" \
-          --query 'SecretString' \
-          --output text 2>/dev/null | jq -r '.ggadmin' 2>/dev/null)
-        if [ -z "$ggadmin_source_pwd" ]; then
-          echo "ERROR: Cannot retrieve existing passwords secret for {{ oracle_goldengate_group.source.tns_alias }}"
-          exit 1
-        fi
-        ggadmin_audit_pwd=$(aws secretsmanager get-secret-value \
-          --secret-id "/oracle/database/{{ oracle_goldengate_group.auditdata.tns_alias }}/passwords" \
-          --query 'SecretString' \
-          --output text 2>/dev/null | jq -r '.ggadmin' 2>/dev/null)
-        if [ -z "$ggadmin_audit_pwd" ]; then
-          echo "ERROR: Cannot retrieve existing passwords secret for {{ oracle_goldengate_group.auditdata.tns_alias }}"
-          exit 1
-        fi
-        ggadmin_mis_pwd=$(aws secretsmanager get-secret-value \
-          --secret-id "/oracle/database/{{ oracle_goldengate_group.mis.tns_alias }}/passwords" \
-          --query 'SecretString' \
-          --output text 2>/dev/null | jq -r '.ggadmin' 2>/dev/null)
-        if [ -z "$ggadmin_mis_pwd" ]; then
-          echo "ERROR: Cannot retrieve existing passwords secret for {{ oracle_goldengate_group.mis.tns_alias }}"
-          exit 1
-        fi
-
         export ORACLE_SID={{ oracle_goldengate_local_db_sid }}
         export ORAENV_ASK=NO
         . oraenv > /dev/null 2>&1
+
+        dbuser_source_pwd=$(aws secretsmanager get-secret-value \
+          --secret-id "/oracle/database/{{ oracle_goldengate_group.source.tns_alias }}/passwords" \
+          --query 'SecretString' \
+          --output text 2>/dev/null | jq -r '.{{ oracle_goldengate_dbuser }}' 2>/dev/null)
+        if [ -z "$dbuser_source_pwd" ]; then
+          echo "ERROR: Cannot retrieve existing passwords secret for {{ oracle_goldengate_group.source.tns_alias }}"
+          exit 1
+        fi
+        {% if oracle_goldengate_deploy_auditdata or oracle_goldengate_deploy_auditref %}
+          dbuser_audit_pwd=$(aws secretsmanager get-secret-value \
+            --secret-id "/oracle/database/{{ oracle_goldengate_group.auditdata.tns_alias }}/passwords" \
+            --query 'SecretString' \
+            --output text 2>/dev/null | jq -r '.{{ oracle_goldengate_dbuser }}' 2>/dev/null)
+          if [ -z "$dbuser_audit_pwd" ]; then
+            echo "ERROR: Cannot retrieve existing passwords secret for {{ oracle_goldengate_group.auditdata.tns_alias }}"
+            exit 1
+          fi
+        {% endif %}
+        {% if oracle_goldengate_deploy_mis %}
+          dbuser_mis_pwd=$(aws secretsmanager get-secret-value \
+            --secret-id "/oracle/database/{{ oracle_goldengate_group.mis.tns_alias }}/passwords" \
+            --query 'SecretString' \
+            --output text 2>/dev/null | jq -r '.{{ oracle_goldengate_dbuser }}' 2>/dev/null)
+          if [ -z "$dbuser_mis_pwd" ]; then
+            echo "ERROR: Cannot retrieve existing passwords secret for {{ oracle_goldengate_group.mis.tns_alias }}"
+            exit 1
+          fi
+        {% endif %}
 
         cd {{ oracle_goldengate_home }}
         ./ggsci << EOF
         ADD CREDENTIALSTORE
         ALTER CREDENTIALSTORE DELETE USER {{ oracle_goldengate_dbuser }}@{{ oracle_goldengate_group.source.tns_alias }} ALIAS '{{ oracle_goldengate_group.source.credential_alias }}'
+        ALTER CREDENTIALSTORE ADD USER {{ oracle_goldengate_dbuser }}@{{ oracle_goldengate_group.source.tns_alias }} PASSWORD '$dbuser_source_pwd' ALIAS '{{ oracle_goldengate_group.source.credential_alias }}'
+        {% if oracle_goldengate_deploy_auditdata or oracle_goldengate_deploy_auditref %}
         ALTER CREDENTIALSTORE DELETE USER {{ oracle_goldengate_dbuser }}@{{ oracle_goldengate_group.auditdata.tns_alias }} ALIAS '{{ oracle_goldengate_group.auditdata.credential_alias }}'
+        ALTER CREDENTIALSTORE ADD USER {{ oracle_goldengate_dbuser }}@{{ oracle_goldengate_group.auditdata.tns_alias }} PASSWORD '$dbuser_audit_pwd' ALIAS '{{ oracle_goldengate_group.auditdata.credential_alias }}'
+        {% endif %}
+        {% if oracle_goldengate_deploy_mis %}
         ALTER CREDENTIALSTORE DELETE USER {{ oracle_goldengate_dbuser }}@{{ oracle_goldengate_group.mis.tns_alias }} ALIAS '{{ oracle_goldengate_group.mis.credential_alias }}'
-        ALTER CREDENTIALSTORE ADD USER {{ oracle_goldengate_dbuser }}@{{ oracle_goldengate_group.source.tns_alias }} PASSWORD "${ggadmin_source_pwd}" ALIAS '{{ oracle_goldengate_group.source.credential_alias }}'
-        ALTER CREDENTIALSTORE ADD USER {{ oracle_goldengate_dbuser }}@{{ oracle_goldengate_group.auditdata.tns_alias }} PASSWORD "${ggadmin_audit_pwd}" ALIAS '{{ oracle_goldengate_group.auditdata.credential_alias }}'
-        ALTER CREDENTIALSTORE ADD USER {{ oracle_goldengate_dbuser }}@{{ oracle_goldengate_group.mis.tns_alias }} PASSWORD "${ggadmin_mis_pwd}" ALIAS '{{ oracle_goldengate_group.mis.credential_alias }}'
+        ALTER CREDENTIALSTORE ADD USER {{ oracle_goldengate_dbuser }}@{{ oracle_goldengate_group.mis.tns_alias }} PASSWORD '$dbuser_mis_pwd' ALIAS '{{ oracle_goldengate_group.mis.credential_alias }}'
+        {% endif %}
         INFO CREDENTIALSTORE
         EXIT
         EOF
@@ -62,7 +70,7 @@
       become_user: "{{ oracle_goldengate_owner }}"
       register: credstore_output
       changed_when: "'Credential store created' in credstore_output.stdout_lines or 'Credential store altered' in credstore_output.stdout_lines"
-      failed_when: credstore_output.rc != 0 and 'already exists' not in credstore_output.stderr
+      failed_when: credstore_output.rc != 0 and 'already exists' not in credstore_output.stderr and 'does not exist' not in credstore_output.stderr
 
     - name: Display credential store configuration output
       ansible.builtin.debug:
