changes prior to testing
output db collection status for an oracle_sid as bool

diff --git a/ansible/roles/oracle-db-monitoring/templates/oracle-health.sh.j2 b/ansible/roles/oracle-db-monitoring/templates/oracle-health.sh.j2
--- a/ansible/roles/oracle-db-monitoring/templates/oracle-health.sh.j2
+++ b/ansible/roles/oracle-db-monitoring/templates/oracle-health.sh.j2
@@ -6,24 +6,24 @@ then
 fi
 
 # We need to make sure this is in the path
-export PATH=$${PATH}:/usr/local/bin
+export PATH=${PATH}:/usr/local/bin
 
 CRSCTL="$(dbhome +ASM)/bin/crsctl"
 
-if [[ -x "$${CRSCTL}" ]]
+if [[ -x "${CRSCTL}" ]]
 then
   # Clustered Oracle
   ORACLE_SID="+ASM"
   ORAENV_ASK="NO"
   . oraenv > /dev/null
 
-  # DB resources names are usually 'ora.$${DB}.db' but some have a suffix after $${DB}
+  # DB resources names are usually 'ora.${DB}.db' but some have a suffix after ${DB}
   DB="$(crsctl status resource | grep -m1 -i ora\.${oracle_sid}.*\.db | cut -f2 -d=)"
 
   # Worth noting here that crsctl exits with code 0 even if you try and find details of a database that doesn't exist
-  STATUS="$(crsctl status resource $${DB} -v | grep STATE_DETAILS | cut -f2 -d= | cut -f1 -d,)"
+  STATUS="$(crsctl status resource ${DB} -v | grep STATE_DETAILS | cut -f2 -d= | cut -f1 -d,)"
 
-  case $${STATUS} in
+  case ${STATUS} in
     "Open")
       exit 0
       ;;
@@ -34,7 +34,7 @@ then
       exit 0
       ;;
     *)
-      echo "Failed to find a valid state for $${DB}" 1>&2
+      echo "Failed to find a valid state for ${DB}" 1>&2
       exit 1
       ;;
   esac
@@ -44,11 +44,11 @@ else
   ORAENV_ASK="NO"
   . oraenv > /dev/null
 
-  $${ORACLE_HOME}/bin/sqlplus / as sysdba <<-EOF > /dev/null
+  ${ORACLE_HOME}/bin/sqlplus / as sysdba <<-EOF > /dev/null
   set heading off
   WHENEVER SQLERROR EXIT SQL.SQLCODE
   select sysdate from dual;
 EOF
 
-  exit "$${?}"
+  exit "${?}"
 fi
